System#screener
  SDK.swift#screener-kit
    Runtime#runtime
      Configuration#configuration
      SessionManager#sessions
      CaptureCoordinator#capture
      MarkerAPI#markers
      Diagnostics#diagnostics
    Capture#capture-system
      CaptureBackend#capture-backend
      UIKitCapture.uikit#uikit-capture
      AppKitCapture.appkit#appkit-capture
      SwiftUICapture.swiftui#swiftui-capture
      ScreenCaptureBackend.optional#screen-capture-kit
    Policy#capture-policy
      HeartbeatSampler#heartbeat
      BurstSampler#burst
      VisualChangeDetector#visual-change
      SettledFrameDetector#settled-frame
      Backpressure#backpressure
    Processing#processing
      ThumbnailRenderer#thumbnail-renderer
      ImageEncoder#image-encoder
      FrameHasher#frame-hasher
      DiffMetrics#diff-metrics
    Semantics#semantics
      AppContextProvider#app-context
      SceneContextProvider#scene-context
      AccessibilitySnapshot#accessibility
      PrivacyFilter#privacy
      RedactionPolicy#redaction
    Persistence#persistence
      TraceWriter#trace-writer
      BlobStore#blob-store
      TimelineWriter#timeline-writer
      RetentionPolicy#retention
  TraceFormat#vtrace
    Manifest#manifest
    Timeline#timeline
      SessionRecord#session-record
      FrameRecord#frame-record
      MarkerRecord#marker-record
      LifecycleRecord#lifecycle-record
      WarningRecord#warning-record
    ArtifactStore#artifacts
      ThumbnailArtifact#thumbnail
      FrameArtifact#frame
      SemanticArtifact#semantic
  Utility.macos#screener-mcp
    Discovery#discovery
      TraceSource#trace-source
      SimulatorTraceSource.simctl#simulator-source
      LocalTraceSource.filesystem#local-source
      DeviceTraceSource.future#device-source
    Reader#reader
      ManifestReader#manifest-reader
      TimelineReader#timeline-reader
      ActiveTraceTailer#active-tailer
      TraceIndex#trace-index
    Presentation#presentation
      ContactSheetRenderer#contact-sheet
      FrameResolver#frame-resolver
      FrameDiff#frame-diff
    MCP#model-context-protocol
      SessionsTool#sessions-tool
      TimelineTool#timeline-tool
      ContactSheetTool#contact-sheet-tool
      FrameTool#frame-tool
      InspectTool#inspect-tool
      DiffTool#diff-tool
  DeviceBridge.future#device-bridge
    Discovery#device-discovery
    Pairing#pairing
    Transport.network-framework#transport
    TraceExport#trace-export
  TestSupport#tests
    FixtureApp#fixture-app
      StaticScreen#static-screen
      AnimatedTransition#animated-transition
      DelayedLayoutChange#delayed-layout-change
      SensitiveContent#sensitive-content
    GoldenTrace#golden-trace
    PerformanceHarness#performance
    CompatibilitySuite#compatibility
